server:
  port: 8082

health:
  message: "Hello from order-service in LOCAL!"

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /order-h2-console

  cloud:
    function:
      definition: pointsFailed
    stream:
      kafka:
        binder:
          brokers: localhost:9092 # ✅ localhost의 Kafka
      bindings:
        orderCreated-out-0:
          destination: order-created
          content-type: application/json

        pointsFailed-in-0:
          destination: points-failed
          group: order-service

    kubernetes:
      config:
        enabled: false
      discovery:
        enabled: false