server:
  port: 8082

health:
  message: "Hello from order-service in LOCAL!"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    function:
      definition: pointsFailed;stockFailed
    stream:
      bindings:
        # Output (DLQ 불필요)
        orderCreated-out-0:
          destination: order-created
          content-type: application/json

        orderCancelled-out-0:
          destination: order-cancelled
          content-type: application/json

        # Input (여기서 처리하다 죽으면 안 됨 -> DLQ 적용)
        pointsFailed-in-0:
          destination: points-failed
          group: order-service
          consumer:
            max-attempts: 3

        stockFailed-in-0:
          destination: stock-failed
          group: order-service
          consumer:
            max-attempts: 3

      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          pointsFailed-in-0:
            consumer:
              enable-dlq: true
              dlq-name: points-failed-dlq
              dlq-partitions: 1
          stockFailed-in-0:
            consumer:
              enable-dlq: true
              dlq-name: stock-failed-dlq
              dlq-partitions: 1

    kubernetes:
      config:
        enabled: false
      discovery:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    tags:
      application: order-service

logging:
  level:
    com.benecia: INFO
    root: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    org.springframework.cloud.stream: WARN
    org.apache.kafka.common.utils.AppInfoParser: ERROR
    org.apache.kafka.common.metrics: ERROR